=== thinfactory/veeam-cloud-connect-api/src/tenants/get_200_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "required": [
    "id",
    "status",
    "subscription_id",
    "username",
    "email",
    "created_at",
    "updated_at"
  ],
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "description": "The unique identifier of the tenant.",
        "type": "integer"
      },
      "status": {
        "description": "The status of the tenant.",
        "type": "string",
        "enum": [
          "active",
          "pending",
          "expired",
          "suspended_invoice_overdue",
          "provisioning",
          "deprovisioning"
        ]
      },
      "subscription_id": {
        "description": "The unique identifier of the subscription entry.",
        "type": "integer"
      },
      "username": {
        "description": "The username of the tenant.",
        "type": "string",
        "minLength": 5,
        "maxLength": 50
      },
      "email": {
        "description": "The email address of the tenant.",
        "type": "string",
        "minLength": 5,
        "maxLength": 60
      },
      "volume_name": {
        "description": "The name of the storage volume the data resides on; only applicable if status is not `pending`.",
        "type": "string"
      },
      "volume_quota": {
        "description": "The quota assigned to the tenant.",
        "type": "integer"
      },
      "volume_used": {
        "description": "The amount of storage in use; only applicable if the value is greater than `0`.",
        "type": "number"
      },
      "volume_available": {
        "description": "The amount of storage available; only applicable if the value is greater than `0`.",
        "type": "number"
      },
      "created_at": {
        "description": "The date the tenant was created.",
        "type": "string"
      },
      "updated_at": {
        "description": "The date the tenant was last modified.",
        "type": "string"
      }
    }
  }
}

=== thinfactory/veeam-cloud-connect-api/src/tenants/id/get_200_example.json
{
  "id": 1,
  "status": "active",
  "subscription_id": 1,
  "username": "google vcc trial",
  "email": "vcc_trial@google.com",
  "volume_name": "VCC-VDM0001-Z",
  "volume_quota": 100,
  "volume_used": 12.1,
  "volume_available": 88.9,
  "created_at": "2015-07-17 09:54:00",
  "updated_at": "2015-07-17 09:54:00"
}

=== thinfactory/veeam-cloud-connect-api/src/tenants/get_200_example.json
[
  {
    "id": 1,
    "status": "active",
    "subscription_id": 1,
    "username": "google vcc trial",
    "email": "vcc_trial@google.com",
    "volume_name": "VCC-VDM0001-Z",
    "volume_quota": 100,
    "volume_used": 12.1,
    "volume_available": 88.9,
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 2,
    "status": "active",
    "subscription_id": 2,
    "username": "google europe north",
    "email": "vcc_eu_north@google.com",
    "volume_name": "VCC-VDM0011-X",
    "volume_quota": 3000,
    "volume_used": 1450.73,
    "volume_available": 1550.27,
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 3,
    "status": "active",
    "subscription_id": 2,
    "username": "google europe west",
    "email": "vcc_eu_west@google.com",
    "volume_name": "VCC-VDM0011-X",
    "volume_quota": 2000,
    "volume_used": 786.2,
    "volume_available": 1214.8,
    "created_at": "2015-07-17 11:06:43",
    "updated_at": "2015-07-17 11:06:43"
  },
  {
    "id": 4,
    "status": "active",
    "subscription_id": 3,
    "username": "google north america",
    "email": "vcc_us_na@google.com",
    "volume_name": "VCC-VDM-0015-L",
    "volume_quota": 1000,
    "volume_used": 391.85,
    "volume_available": 609.15,
    "created_at": "2015-07-17 11:08:11",
    "updated_at": "2015-07-17 11:08:11"
  }
]
