=== thinfactory/veeam-cloud-connect-api/src/subscriptions/id/recursive/get_200_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "id",
    "status",
    "catalog_id",
    "period_start",
    "created_at",
    "updated_at"
  ],
  "properties": {
    "id": {
      "description": "The unique identifier of the subscription.",
      "type": "integer"
    },
    "status": {
      "description": "The status of the subscription.",
      "type": "string",
      "enum": [
        "trial",
        "active",
        "expired",
        "suspended_invoice_overdue"
      ]
    },
    "catalog_id": {
      "description": "The unique identifier of the catalog entry.",
      "type": "integer"
    },
    "period_start": {
      "description": "The date the subscription was started.",
      "type": "string",
      "pattern": "^(19|20)\\d\\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$"
    },
    "period_expire": {
      "description": "The date the subscription will expire; only applicable on pre-paid subscriptions.",
      "type": "string",
      "pattern": "^(19|20)\\d\\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$"
    },
    "sku_quantity": {
      "description": "The SKU quantity; only applicable on pre-paid subscriptions.",
      "type": "integer"
    },
    "sku_used": {
      "description": "The amount SKU assigned to tenants; only applicable if the value is greater than `0`.",
      "type": "integer"
    },
    "$catalog": {
      "description": "A reference view of the catalog entry.",
      "type": "object"
    },
    "$tenants": {
      "description": "A reference view of the tenants, excluding its $subscription reference view.",
      "type": "array"
    },
    "created_at": {
      "description": "The date the subscription was created.",
      "type": "string"
    },
    "updated_at": {
      "description": "The date the subscription was last modified.",
      "type": "string"
    }
  }
}

=== thinfactory/veeam-cloud-connect-api/src/subscriptions/get_200_example.json
[
  {
    "id": 1,
    "status": "trial",
    "catalog_id": 1,
    "period_start": "2015-07-17",
    "sku_used": 100,
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 2,
    "status": "active",
    "catalog_id": 1,
    "period_start": "2015-07-17",
    "sku_used": 5000,
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 3,
    "status": "active",
    "catalog_id": 2,
    "period_start": "2015-07-17",
    "period_expire": "2015-10-17",
    "sku_quantity": 1000,
    "sku_used": 1000,
    "created_at": "2015-07-17 11:01:14",
    "updated_at": "2015-07-17 11:01:14"
  }
]

=== thinfactory/veeam-cloud-connect-api/src/subscriptions/recursive/get_200_example.json
[
  {
    "id": 1,
    "status": "trial",
    "catalog_id": 1,
    "period_start": "2015-07-17",
    "sku_used": 100,
    "$catalog": {
      "id": 1,
      "sku_label": "VCC-REP-BRU1",
      "sku_tag": "Veeam Cloud Connect @ Mobistar Enterprise Services, Brussels",
      "sku_description": "An off-site backup repository for Veeam located in the Mobistar Enterprise Services datacenter.",
      "sku_orderable": true,
      "sku_quantity_max": 5000,
      "sku_price": 0.45,
      "sku_trial": 30,
      "sku_type": "subscription",
      "sku_discounts": {
        "3": 2,
        "6": 3,
        "12": 5
      },
      "properties": {
        "vcc_hostname": "https://vcc-bru1.cloudplaza.eu",
        "vcc_wan_acceleration": true,
        "datacenter_tag": "BRU1",
        "datacenter_name": "Mobistar Enterprise Services",
        "datacenter_address": "Leuvensesteenweg 641",
        "datacenter_zip": "1930",
        "datacenter_city": "Zaventem",
        "datacenter_country": "Belgium"
      },
      "created_at": "2015-07-17 09:54:00",
      "updated_at": "2015-07-17 09:54:00"
    },
    "$tenants": [
      {
        "id": 1,
        "status": "active",
        "subscription_id": 1,
        "username": "google vcc trial",
        "email": "vcc_trial@google.com",
        "volume_name": "VCC-VDM0001-Z",
        "volume_quota": 100,
        "volume_used": 12.1,
        "volume_available": 88.9,
        "created_at": "2015-07-17 09:54:00",
        "updated_at": "2015-07-17 09:54:00"
      }
    ],
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 2,
    "status": "active",
    "catalog_id": 1,
    "period_start": "2015-07-17",
    "sku_used": 5000,
    "$catalog": {
      "id": 1,
      "sku_label": "VCC-REP-BRU1",
      "sku_tag": "Veeam Cloud Connect @ Mobistar Enterprise Services, Brussels",
      "sku_description": "An off-site backup repository for Veeam located in the Mobistar Enterprise Services datacenter.",
      "sku_orderable": true,
      "sku_quantity_max": 5000,
      "sku_price": 0.45,
      "sku_trial": 30,
      "sku_type": "subscription",
      "sku_discounts": {
        "3": 2,
        "6": 3,
        "12": 5
      },
      "properties": {
        "vcc_hostname": "https://vcc-bru1.cloudplaza.eu",
        "vcc_wan_acceleration": true,
        "datacenter_tag": "BRU1",
        "datacenter_name": "Mobistar Enterprise Services",
        "datacenter_address": "Leuvensesteenweg 641",
        "datacenter_zip": "1930",
        "datacenter_city": "Zaventem",
        "datacenter_country": "Belgium"
      },
      "created_at": "2015-07-17 09:54:00",
      "updated_at": "2015-07-17 09:54:00"
    },
    "$tenants": [
      {
        "id": 2,
        "status": "active",
        "subscription_id": 2,
        "username": "google europe north",
        "email": "vcc_eu_north@google.com",
        "volume_name": "VCC-VDM0011-X",
        "volume_quota": 3000,
        "volume_used": 1450.73,
        "volume_available": 1550.27,
        "created_at": "2015-07-17 09:54:00",
        "updated_at": "2015-07-17 09:54:00"
      },
      {
        "id": 3,
        "status": "active",
        "subscription_id": 2,
        "username": "google europe west",
        "email": "vcc_eu_west@google.com",
        "volume_name": "VCC-VDM0011-X",
        "volume_quota": 2000,
        "volume_used": 786.2,
        "volume_available": 1214.8,
        "created_at": "2015-07-17 11:06:43",
        "updated_at": "2015-07-17 11:06:43"
      }
    ],
    "created_at": "2015-07-17 09:54:00",
    "updated_at": "2015-07-17 09:54:00"
  },
  {
    "id": 3,
    "status": "active",
    "catalog_id": 2,
    "period_start": "2015-07-17",
    "period_expire": "2015-10-17",
    "sku_quantity": 1000,
    "sku_used": 1000,
    "$catalog": {
      "id": 2,
      "sku_label": "VCC-REP-BRU2",
      "sku_tag": "Veeam Cloud Connect @ Belgacom Netcenter II, Brussels",
      "sku_description": "An off-site backup repository for Veeam located in the Belgacom Netcenter II datacenter.",
      "sku_orderable": true,
      "sku_quantity_max": 2000,
      "sku_price": 0.45,
      "sku_trial": 30,
      "sku_type": "subscription",
      "sku_discounts": {
        "3": 2,
        "6": 3,
        "12": 5
      },
      "properties": {
        "vcc_hostname": "https://vcc-bru2.cloudplaza.eu",
        "vcc_wan_acceleration": true,
        "datacenter_tag": "BRU2",
        "datacenter_name": "Belgacom Netcenter II",
        "datacenter_address": "Ritterwegelaan 2",
        "datacenter_zip": "1830",
        "datacenter_city": "Machelen",
        "datacenter_country": "Belgium"
      },
      "created_at": "2015-07-17 09:54:00",
      "updated_at": "2015-07-17 09:54:00"
    },
    "$tenants": [
      {
        "id": 4,
        "status": "active",
        "subscription_id": 3,
        "username": "google north america",
        "email": "vcc_us_na@google.com",
        "volume_name": "VCC-VDM-0015-L",
        "volume_quota": 1000,
        "volume_used": 391.85,
        "volume_available": 609.15,
        "created_at": "2015-07-17 11:08:11",
        "updated_at": "2015-07-17 11:08:11"
      }
    ],
    "created_at": "2015-07-17 11:01:14",
    "updated_at": "2015-07-17 11:01:14"
  }
]
