=== thinfactory/veeam-cloud-connect-api/src/account/get_200_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "id",
    "username",
    "created_at",
    "updated_at"
  ],
  "properties": {
    "id": {
      "description": "The unique identifier of the account.",
      "type": "integer"
    },
    "username": {
      "description": "The username of the account.",
      "type": "string",
      "minLength": 5,
      "maxLength": 50
    },
    "email": {
      "description": "The email address of the account.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_organization": {
      "description": "The legal name of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_vat": {
      "description": "The VAT number of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 20
    },
    "billing_contact": {
      "description": "The name of the contact person or department to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_email": {
      "description": "The email address of the contact person or department to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_address": {
      "description": "The address of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_address2": {
      "description": "Additional line for address of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_zip": {
      "description": "The zip code of the billing address.",
      "type": "string",
      "minLength": 4,
      "maxLength": 30
    },
    "billing_city": {
      "description": "The city of the billing address.",
      "type": "string",
      "minLength": 5,
      "maxLength": 30
    },
    "billing_country": {
      "description": "The ISO 3166-1 alpha-2 country code.",
      "type": "string",
      "minLength": 2,
      "maxLength": 2
    },
    "created_at": {
      "description": "The date the account was created.",
      "type": "string"
    },
    "updated_at": {
      "description": "The date the account was last modified.",
      "type": "string"
    }
  }
}

=== thinfactory/veeam-cloud-connect-api/src/account/get_200_example.json
{
  "id": 1,
  "username": "google inc",
  "email": "vcc@google.com",
  "billing_organization": "Google Inc.",
  "billing_vat": "US EIN 77-0493581",
  "billing_contact": "Finance Department",
  "billing_email": "finance@google.com",
  "billing_address": "1600 Amphitheatre Parkway",
  "billing_zip": "CA 94043",
  "billing_city": "Mountain View",
  "billing_country": "US",
  "created_at": "2015-07-17 09:54:00",
  "updated_at": "2015-07-17 09:54:00"
}
