=== thinfactory/veeam-cloud-connect-api/src/account/post_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "username",
    "password"
  ],
  "properties": {
    "username": {
      "description": "The username of the account.",
      "type": "string",
      "minLength": 5,
      "maxLength": 50
    },
    "password": {
      "description": "The password of the account.",
      "type": "string",
      "minLength": 5,
      "maxLength": 50
    },
    "email": {
      "description": "The email address of the account.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_organization": {
      "description": "The legal name of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_vat": {
      "description": "The VAT number of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 20
    },
    "billing_contact": {
      "description": "The name of the contact person or department to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_email": {
      "description": "The email address of the contact person or department to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_address": {
      "description": "The address of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_address2": {
      "description": "Additional line for address of the entity to invoice.",
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "billing_zip": {
      "description": "The zip code of the billing address.",
      "type": "string",
      "minLength": 4,
      "maxLength": 30
    },
    "billing_city": {
      "description": "The city of the billing address.",
      "type": "string",
      "minLength": 5,
      "maxLength": 30
    },
    "billing_country": {
      "description": "The ISO 3166-1 alpha-2 country code.",
      "type": "string",
      "minLength": 2,
      "maxLength": 2
    }
  }
}

=== thinfactory/veeam-cloud-connect-api/src/account/post_example.json
{
  "username": "Google Inc",
  "password": "my super awesome password",
  "email": "vcc@google.com",
  "billing_organization": "Google Inc.",
  "billing_vat": "US EIN 77-0493581",
  "billing_contact": "Finance Department",
  "billing_email": "finance@google.com",
  "billing_address": "1600 Amphitheatre Parkway",
  "billing_zip": "CA 94043",
  "billing_city": "Mountain View",
  "billing_country": "US"
}
